import { readFileSync } from 'node:fs';
import { describe, it, expect, beforeAll } from 'vitest';
import Papa from 'papaparse';
import { LocalExtractionProvider } from './localProvider';
import type { ExtractionContext } from './types';

/**
 * Runs the local extraction provider against the synthetic PDF fixtures from
 * issue #237, generated by `scripts/generate-synthetic-invoice-pdfs.py`.
 *
 * These are fictitious documents, not the real anonymised invoices requested
 * in #202 — the point here is exercising real PDF/image bytes and the
 * multiple visual layouts a scanner or download produces, which the rest of
 * this test suite (localProvider.test.ts, invoiceParser.test.ts) never does:
 * those feed the provider hand-written plain-text buffers.
 *
 * Not every field is asserted for every fixture. Where the local extractor's
 * label-based heuristics get a realistic tabular layout wrong, the test
 * records the current (imperfect) behaviour rather than asserting a value
 * that isn't actually produced — a known gap that stays visible is better
 * than a green test that quietly expects the wrong thing (AGENTS.md #7).
 */

const FIXTURES_DIR = new URL('../../../fixtures/documents/synthetic/', import.meta.url).pathname;

interface FixtureRow {
  file: string; doc_type: string; direction: string; issuer: string; recipient: string;
  invoice_no: string; date: string; currency: string; net: string; vat: string; gross: string;
  quirks: string;
}

function toMinor(euro: string): number {
  return Math.round(Number.parseFloat(euro) * 100);
}

const context: ExtractionContext = {
  knownSuppliers: [],
  knownCustomers: [],
  companyVatNumber: 'IE3384127K',
  companyName: 'Harbour Paws Pet Care Ltd',
  baseCurrency: 'EUR',
  availableAccountCodes: [],
  availableVatTreatments: [
    { code: 'IE_STD', name: 'Irish standard rate', description: null },
    { code: 'IE_ZERO', name: 'Irish zero-rated', description: null },
    { code: 'EU_SERVICES_RCV', name: 'EU services received', description: null },
    { code: 'NON_EU_SERVICES_RCV', name: 'Non-EU services received', description: null },
    { code: 'EU_GOODS_ACQ', name: 'EU acquisition of goods', description: null },
    { code: 'IMPORT_PA', name: 'Import postponed accounting', description: null },
  ],
};

const provider = new LocalExtractionProvider();

let rows: FixtureRow[];

beforeAll(() => {
  const csv = readFileSync(`${FIXTURES_DIR}invoice_index.csv`, 'utf8');
  rows = Papa.parse<FixtureRow>(csv, { header: true, skipEmptyLines: true }).data;
  expect(rows.length).toBeGreaterThan(15);
});

function extract(file: string) {
  const content = readFileSync(`${FIXTURES_DIR}${file}`);
  return provider.extract({ content, mimeType: 'application/pdf', filename: file, context });
}

describe('synthetic invoice fixtures (issue #237)', () => {
  it('the two degraded scans have no usable text layer and are flagged for OCR', async () => {
    for (const file of ['16_pi_vetmed_scan.pdf', '17_pi_topoil_photocopy.pdf']) {
      const result = await extract(file);
      expect(result.status).toBe('failed');
      expect(result.extractedText.trim().length).toBeLessThan(40);
      expect(result.observations.join(' ')).toContain('scan');
    }
  });

  it('every non-scanned fixture is read, with the right currency', async () => {
    const scanned = new Set(['16_pi_vetmed_scan.pdf', '17_pi_topoil_photocopy.pdf']);
    for (const row of rows) {
      if (scanned.has(row.file)) continue;
      const result = await extract(row.file);
      expect(result.status, `${row.file} should not fail to read`).not.toBe('failed');
      expect(result.extractedText.length, `${row.file} should have a real text layer`).toBeGreaterThan(40);
      expect(result.fields.currency.value, `${row.file} currency`).toBe(row.currency);
    }
  });

  it('reads the invoice total correctly on every template except the two unreadable scans', async () => {
    const scanned = new Set(['16_pi_vetmed_scan.pdf', '17_pi_topoil_photocopy.pdf']);
    for (const row of rows) {
      if (scanned.has(row.file)) continue;
      const result = await extract(row.file);
      expect(result.fields.grossMinor.value, `${row.file} gross`).toBe(toMinor(row.gross));
    }
  });

  it('reads a credit note totalled under a "CREDIT (EUR)" label with no "total"/"due" wording (issue #276)', async () => {
    // The totals box is the run of short label-amount rows, and a "credit"
    // label there is the total — as printed, negative on this document.
    const result = await extract('08_cn_groompro_credit.pdf');
    expect(result.fields.documentType.value).toBe('credit_note');
    expect(result.fields.grossMinor.value).toBe(toMinor('-96.3'));
  });

  it('prefers the totals-box figure over a "balance due" phrase in a free-text note (issue #276)', async () => {
    // The invoice notes mention a running "balance due EUR 469.66" after a
    // credit note was applied. The totals box below it carries the real
    // "TOTAL (EUR) 565.96" row, and a label matched there outranks the same
    // words appearing in a note.
    const result = await extract('11_pi_groompro_565.pdf');
    expect(result.fields.grossMinor.value).toBe(toMinor('565.96'));
  });
});
